name: Wake Up Render Server Every 10 Minutes

on:
  schedule:
    - cron: '0 * * * *'
    - cron: '10 * * * *'
    - cron: '20 * * * *'
    - cron: '30 * * * *'
    - cron: '40 * * * *'
    - cron: '50 * * * *'
jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Wake up Render Server
        run: curl https://symfony-9z0y.onrender.com
