name: Wake Up Render Server Every Minutes

on:
  schedule:
    - cron: '*/1 * * * *'
    
jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Wake up Render Server
        run: curl https://symfony-9z0y.onrender.com
