name: Wake Up Render Server Every Minutes

on:
  push:
    
jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Wake up Render Server
        run: curl https://symfony-9z0y.onrender.com
